[package]
name = "blockframe"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
rand = "0.9.2"
reed-solomon-simd = "3.0"

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
blake3 = "1.5"
sysinfo = "0.37.2"
memmap2 = "0.9.9"
rayon = "1.11.0"

[profile.release]
debug = true  # Enable symbols for profiling
opt-level = 3 # Still fully optimized

[dev-dependencies]
tempfile = "3.23.0"
